### ISSUE TITLE
Gitlab.yml needs an update to use PS1 instead of cmd script.

### ISSUE THREAD

**Issue by olivier-spinelli** [CK-Build/CKli#5]
![image](https://user-images.githubusercontent.com/1583378/72911022-af32e580-3d39-11ea-86f6-d08d527b7561.png)

**Comment by bcrosnier** [comment]
We use the `script` instruction instead of calling the shell directly:

https://github.com/CK-Build/CKli/blob/ba0d196019376a5ada88fb39228ef8fbf8e45bbe/Plugins/CK.Env.Plugin.GitLab/GitLabFile.cs#L41

But the _runner_ (as in, the configuration in the host machine) should be configured to use `powershell` instead of `cmd`. This is detailed somewhere in https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runners-section .

**Comment by Kuinox** [comment]
As this is a CI runner config issue and not an issue with CKli, i close this issue.
